#!/usr/bin/env node
/**
 * Generate frontend/.env.local from deployments/testnet.json.
 * Safe to run after every publish — output is gitignored.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadTestnetDeployment } from './load-deployment.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const { packageId, packagePublishedAt, reputationRegistryId } = loadTestnetDeployment();

const env = `# Generated by scripts/sync-env.mjs — do not commit
NEXT_PUBLIC_PACKAGE_ID=${packageId}
NEXT_PUBLIC_PACKAGE_PUBLISHED_AT=${packagePublishedAt}
NEXT_PUBLIC_REPUTATION_REGISTRY_ID=${reputationRegistryId}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
`;

writeFileSync(join(ROOT, 'frontend/.env.local'), env, 'utf8');
console.log('Wrote frontend/.env.local from deployments/testnet.json');
